### ISSUE TITLE
gun recoil

### ISSUE THREAD

**Issue by soapstain22** [soapstain22/attack-of-the-war-fighter-inners#15]
when you shoot, you get pushed back a little. Sniper rifle will send you flying back, rocket too. pistol is lightweight, bow is none.

**Comment by DidierF** [comment]
Working on this now.

**Comment by DidierF** [comment]
@soapstain22 Do you want this to send the player back when they're moving too?

**Comment by soapstain22** [comment]
> @soapstain22 Do you want this to send the player back when they're moving too?

yea, even jumping. while ur at it you could add recoil. shouldnt be too complicated.

**Comment by soapstain22** [comment]
#33 resolved
